`timescale 1ns/1ps
// Directed hardware smoke test for Phase 13 stage 8: rtl/soc/soc_top.v's
// NUM_HARTS=2. Nothing else in `make verify`/`make verify_ooo` builds the
// SoC with more than one hart, so this is the only place hart 1's own
// cpu_core/cpu_wb/wb_ptw triple, the interconnect's second data/fetch/
// walker slot, CLINT's second timer, and PLIC's second context pair
// actually run.
//
// software/soc/bootrom.c does not know a second hart exists yet (it still
// runs the same single-hart boot flow on whichever hart fetches it), so
// this does not boot through the real boot ROM the way sim/tb_soc.v does -
// RESET_PC is pointed straight into RAM instead, preloaded with a small
// hand-assembled program (sim/soc2hart.hex, generated by this Makefile the
// same way sim/jtagram.hex is: field-packing helpers, not hand-typed hex).
// Each hart reads its own `mhartid`, branches to its own path, and stores a
// hart-specific sentinel to a hart-specific RAM word:
//
//   csrrs x1, mhartid, x0
//   lui   x2, 0x80000        ; x2 = RAM base
//   bne   x1, x0, HART1
//   ; hart 0
//   addi  x2, x2, 0x100
//   lui   x3, 0xAAAA0
//   sw    x3, 0(x2)          ; RAM[0x8000_0100] = 0xAAAA0000
//   jal   x0, 0              ; self-loop
// HART1:
//   addi  x2, x2, 0x104
//   lui   x3, 0xBBBB0
//   sw    x3, 0(x2)          ; RAM[0x8000_0104] = 0xBBBB0000
//   jal   x0, 0              ; self-loop
//
// This proves the hardware wiring - both harts fetch, execute and reach the
// shared bus independently, arbitration doesn't starve or corrupt either
// one, and the DCACHE_ENABLE=0 bypass this stage forces at NUM_HARTS>1
// doesn't break an ordinary word store. It deliberately does not exercise
// LR/SC cross-hart coherence: rtl/soc/reservation_monitor.v is still wired
// to nothing (docs/roadmap.md's Phase 13 entry), so that remains a
// separate, later directed test once a later stage connects it.
module tb_soc_2hart;
    reg clk = 0;
    reg rst = 1;

    wire uart_tx;
    wire spi_sck, spi_mosi, spi_miso, spi_cs_n;
    wire [15:0] gpio_out, gpio_dir;
    wire        pwm_out;
    wire        trap;
    wire [15:0] gpio_in = 16'b0;

    soc_top #(
        .NUM_HARTS(2),
        .RESET_PC(32'h8000_0000),
        .RAM_BYTES(1024),
        .RAM_INIT_FILE("soc2hart.hex")
    ) DUT (
        .clk(clk), .rst(rst),
        .jtag_tck(1'b0), .jtag_tms(1'b0), .jtag_tdi(1'b0),
        .jtag_tdo(), .jtag_tdo_oe(),
        .uart_tx(uart_tx), .uart_rx(1'b1),
        .gpio_in(gpio_in), .gpio_out(gpio_out), .gpio_dir(gpio_dir),
        .spi_sck(spi_sck), .spi_mosi(spi_mosi),
        .spi_miso(spi_miso), .spi_cs_n(spi_cs_n),
        .pwm_out(pwm_out),
        // No SDRAM traffic in this test - both sentinels land in block RAM
        // at 0x8000_0000, well below the SDRAM window at 0x9000_0000.
        .sdram_dq_i(16'b0),
        .trap(trap)
    );

    localparam CLK_PERIOD = 40;  // 25 MHz, matching soc_top's own CLK_HZ default
    always #(CLK_PERIOD / 2) clk = ~clk;

    integer failures = 0;
    task check(input [511:0] name, input [31:0] got, input [31:0] want);
        begin
            if (got !== want) begin
                $display("  FAIL %0s: got %08h expected %08h", name, got, want);
                failures = failures + 1;
            end else begin
                $display("  ok   %0s: %08h", name, got);
            end
        end
    endtask

    initial begin
        repeat (4) @(posedge clk);
        rst = 0;

        // Generous margin: 11 instructions each, over a real Wishbone bus
        // with wait states and two-hart arbitration, not the zero-latency
        // memory sim/tb_cpu_resv_ports.v gets away with tighter bounds on.
        repeat (2000) @(posedge clk);

        check("hart 0 wrote its sentinel to RAM[0x8000_0100]",
              DUT.RAM.mem[64], 32'hAAAA0000);
        check("hart 1 wrote its sentinel to RAM[0x8000_0104]",
              DUT.RAM.mem[65], 32'hBBBB0000);
        check("hart 0 never trapped", {31'b0, trap}, 32'b0);

        if (failures == 0) $display("\nSOC-2HART-TEST: PASS");
        else                $display("\nSOC-2HART-TEST: FAIL (%0d)", failures);
        $finish;
    end

    initial begin
        #1_000_000;
        $display("\nSOC-2HART-TEST: FAIL (timeout)");
        $finish;
    end
endmodule
