#!/usr/bin/env python3
"""Generates software/soc/npu_layer_data.h: a tiny quantized dense layer
for rtl/soc/wb_npu.v (Phase 14) - NPU_LAYER_OUT output neurons, each a
NPU_VEC_LEN-wide signed int8 dot product against one shared activation
vector. This is the smallest thing that is genuinely a "layer" (a real
matrix-vector multiply) rather than the single dot product
software/soc/main.c's own test_npu() already covers - docs/roadmap.md's
Phase 14 "Done when" bar asks for "a single small layer", not one MAC.

The expected outputs below are computed here, in Python, independently
of both the C code that will exercise the peripheral and of
rtl/soc/wb_npu.v's own Verilog arithmetic - the same role a plain
NumPy/C int8 reference plays for this project's own RISC-V ISA tests
(Spike). The seed is fixed so this is reproducible; it was picked by a
short search (see below) for the one property that actually matters for
a test to be non-vacuous: every neuron's expected output is nonzero and
no two collide, so a sign error, a dropped term, or a neuron mix-up
would all visibly change the result rather than passing by coincidence.
"""
import random

VEC_LEN = 16
OUT = 4


def build(seed):
    rng = random.Random(seed)
    a = [rng.randint(-128, 127) for _ in range(VEC_LEN)]
    w = [[rng.randint(-128, 127) for _ in range(VEC_LEN)] for _ in range(OUT)]
    expected = [sum(a[i] * w[n][i] for i in range(VEC_LEN)) for n in range(OUT)]
    return a, w, expected


def acceptable(expected):
    if any(v == 0 for v in expected):
        return False
    return len(set(expected)) == len(expected)


SEED = None
for candidate in range(1, 10000):
    a, w, expected = build(candidate)
    if acceptable(expected):
        SEED = candidate
        break
assert SEED is not None, "no acceptable seed found in range"

lines = []
lines.append("/* Auto-generated by software/soc/gen_npu_layer.py - do not hand-edit.")
lines.append(" * Regenerate with: python3 software/soc/gen_npu_layer.py > \\")
lines.append(" *                  software/soc/npu_layer_data.h")
lines.append(f" * seed = {SEED} */")
lines.append("#ifndef NPU_LAYER_DATA_H")
lines.append("#define NPU_LAYER_DATA_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append(f"#define NPU_LAYER_OUT {OUT}")
lines.append("")
lines.append(f"static const int8_t npu_layer_a[{VEC_LEN}] = {{")
lines.append("    " + ", ".join(str(x) for x in a))
lines.append("};")
lines.append("")
lines.append(f"static const int8_t npu_layer_w[NPU_LAYER_OUT][{VEC_LEN}] = {{")
for row in w:
    lines.append("    { " + ", ".join(str(x) for x in row) + " },")
lines.append("};")
lines.append("")
lines.append("static const int32_t npu_layer_expected[NPU_LAYER_OUT] = {")
lines.append("    " + ", ".join(str(x) for x in expected))
lines.append("};")
lines.append("")
lines.append("#endif /* NPU_LAYER_DATA_H */")

print("\n".join(lines))
