#!/usr/bin/env python3
"""Generates software/soc/fir_workload_data.h: a real 8-tap lowpass FIR
filter (rtl/soc/wb_fir.v, Phase 11) applied to a synthetic signal -
docs/roadmap.md's Phase 11 "Done when" bar's own obvious candidate,
"an audio FIR filter... with an existing reference implementation to
check correctness against."

Coefficients: a windowed-sinc lowpass design (Hamming window, cutoff
fc=0.15 of the Nyquist rate), unity DC gain, scaled by 4096 and rounded
to int16 - a real filter shape, not arbitrary test values, and small
enough that no term of the convolution below can reach saturation
(verified by construction: max |coefficient| * max |sample| * N_TAPS is
checked to stay inside int32 range before this script ever emits a
header).

Input: 128 samples of a low frequency (3 cycles over the signal) plus a
higher frequency (30 cycles - well past the filter's own cutoff, so a
correct lowpass filter measurably attenuates it) component, quantized to
int16 - the same "does this look like the intended filter" check the
expected-output values below let a reader sanity-check independently of
the bit-exact comparison the C test actually performs.

Expected outputs: a sliding-window convolution computed here, in Python,
independently of both the RTL and the C test that will exercise it - the
same role a plain NumPy/C reference plays for this project's own RISC-V
ISA tests against Spike.
"""
import math

N_TAPS = 8
WORKLOAD_LEN = 128
COEF_SCALE = 4096


def build_coefficients():
    fc = 0.15
    m = (N_TAPS - 1) / 2.0
    taps = []
    for n in range(N_TAPS):
        x = n - m
        ideal = 2 * fc if x == 0 else math.sin(2 * math.pi * fc * x) / (math.pi * x)
        window = 0.54 - 0.46 * math.cos(2 * math.pi * n / (N_TAPS - 1))
        taps.append(ideal * window)
    total = sum(taps)
    taps = [t / total for t in taps]   # unity DC gain
    return [round(t * COEF_SCALE) for t in taps]


def build_input():
    samples = []
    for n in range(WORKLOAD_LEN):
        low = 8000 * math.sin(2 * math.pi * 3 * n / WORKLOAD_LEN)
        high = 4000 * math.sin(2 * math.pi * 30 * n / WORKLOAD_LEN)
        samples.append(round(low + high))
    return samples


def convolve(coef, samples):
    hist = [0] * N_TAPS
    out = []
    for x in samples:
        hist = [x] + hist[:-1]
        acc = sum(coef[k] * hist[k] for k in range(N_TAPS))
        out.append(acc)
    return out


coef = build_coefficients()
samples = build_input()
expected = convolve(coef, samples)

for c in coef:
    assert -32768 <= c <= 32767, f"coefficient {c} does not fit int16"
for s in samples:
    assert -32768 <= s <= 32767, f"sample {s} does not fit int16"
for e in expected:
    assert -2147483648 <= e <= 2147483647, f"expected {e} does not fit int32 - saturation would trigger"

lines = []
lines.append("/* Auto-generated by software/soc/gen_fir_workload.py - do not hand-edit.")
lines.append(" * Regenerate with: python3 software/soc/gen_fir_workload.py > \\")
lines.append(" *                  software/soc/fir_workload_data.h */")
lines.append("#ifndef FIR_WORKLOAD_DATA_H")
lines.append("#define FIR_WORKLOAD_DATA_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append(f"#define FIR_WORKLOAD_LEN {WORKLOAD_LEN}")
lines.append("")
lines.append(f"static const int16_t fir_workload_coef[{N_TAPS}] = {{")
lines.append("    " + ", ".join(str(c) for c in coef))
lines.append("};")
lines.append("")
lines.append(f"static const int16_t fir_workload_input[FIR_WORKLOAD_LEN] = {{")
for i in range(0, WORKLOAD_LEN, 8):
    lines.append("    " + ", ".join(str(s) for s in samples[i:i+8]) + ",")
lines.append("};")
lines.append("")
lines.append("static const int32_t fir_workload_expected[FIR_WORKLOAD_LEN] = {")
for i in range(0, WORKLOAD_LEN, 8):
    lines.append("    " + ", ".join(str(e) for e in expected[i:i+8]) + ",")
lines.append("};")
lines.append("")
lines.append("#endif /* FIR_WORKLOAD_DATA_H */")

print("\n".join(lines))
