#!/usr/bin/env python3
"""Generates a dtb_blob header: this project's own real device tree
(dts/soc_$(CORE).dtb, built by `make dtb` from dts/soc.dts) embedded as a C
byte array, so the boot ROM (software/soc/bootrom.c) has a real flattened
device tree to hand a loaded program's a1 - the RISC-V firmware entry
convention (a0 = hart ID, a1 = device tree address) every real M-mode
firmware (OpenSBI included) expects, and which this boot ROM's own
software/opensbi/sbi_stub.S comment already named as "the boot ROM's
eventual job."

Embedded rather than loaded at boot: the boot ROM's own three loading
paths (RAM-preload, UART, SD card) all load whatever program is being
booted, not a second, separate device-tree blob, and the boot ROM's own
16 KB budget has ample room (dts/soc_$(CORE).dtb is ~3 KB) to carry its
own copy in .rodata instead of inventing a second loading mechanism just
for it.

Takes the source .dtb path as its one argument (default dts/soc.dtb, for
a manual, no-Makefile invocation only). The Makefile always passes the
real one explicitly - dts/soc_$(CORE).dtb - because the two cpu nodes'
own `compatible` strings vary with $(CORE) (Phase 15, Stage 3's second
half; see dts/soc.dts's own header for why), and a single shared,
CORE-independent dtb_blob.h would silently embed one CORE's compatible
strings into every other CORE's boot ROM - undetectable by Make's own
mtime-based rebuild tracking, since nothing about switching $(CORE)
touches a file's mtime. docs/roadmap.md's Phase 15 entry has the full
account of that hazard and why this script's own output path is
$(CORE)-suffixed too (dtb_blob_$(CORE).h, chosen by the Makefile, not by
this script).
"""

import sys

DTB_PATH = sys.argv[1] if len(sys.argv) > 1 else "dts/soc.dtb"

with open(DTB_PATH, "rb") as f:
    data = f.read()

lines = []
lines.append("/* Auto-generated by software/soc/gen_dtb_blob.py from")
lines.append(f" * {DTB_PATH} - do not hand-edit. Regenerate with:")
lines.append(" *   make dtb && python3 software/soc/gen_dtb_blob.py \\")
lines.append(f" *                       {DTB_PATH} > <output> */")
lines.append("#ifndef DTB_BLOB_H")
lines.append("#define DTB_BLOB_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append(f"#define BOOT_DTB_LEN {len(data)}u")
lines.append("")
lines.append("static const uint8_t boot_dtb[BOOT_DTB_LEN] = {")
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
lines.append("};")
lines.append("")
lines.append("#endif /* DTB_BLOB_H */")

print("\n".join(lines))
