#!/usr/bin/env python3
"""Generates software/soc/npu_dma_workload_data.h: a real quantized dense
layer at DMA scale - NPU_DMA_OUT output neurons, each a NPU_DMA_INPUT_DIM
-wide signed int8 dot product against one shared activation vector.

The same shape software/soc/gen_npu_layer.py already built (Phase 14
Stage 2, a "single small layer"), but eight times the input width -
128 rather than 16 - specifically because that width cannot be reached
through the original MMIO path's own fixed VEC_LEN register file at
all. This is the workload rtl/soc/wb_npu.v's own DMA master port
(Stage 3) exists to make possible, exercised at the size that is
actually the point of it.

Expected outputs are computed here, in Python, independently of both
the C code that will exercise the peripheral and of rtl/soc/wb_npu.v's
own Verilog arithmetic - the same role a plain NumPy/C int8 reference
plays for this project's own RISC-V ISA tests against Spike. The seed
is fixed for reproducibility, picked (the same way Stage 2's own
generator was) so every neuron's expected output is nonzero and no two
collide - a sign error, a dropped term, or a neuron mix-up would all
visibly change the result rather than passing by coincidence.
"""
import random

INPUT_DIM = 128
OUT = 4


def build(seed):
    rng = random.Random(seed)
    a = [rng.randint(-128, 127) for _ in range(INPUT_DIM)]
    w = [[rng.randint(-128, 127) for _ in range(INPUT_DIM)] for _ in range(OUT)]
    expected = [sum(a[i] * w[n][i] for i in range(INPUT_DIM)) for n in range(OUT)]
    return a, w, expected


def acceptable(expected):
    if any(v == 0 for v in expected):
        return False
    return len(set(expected)) == len(expected)


SEED = None
for candidate in range(1, 10000):
    a, w, expected = build(candidate)
    if acceptable(expected):
        SEED = candidate
        break
assert SEED is not None, "no acceptable seed found in range"

lines = []
lines.append("/* Auto-generated by software/soc/gen_npu_dma_workload.py - do not")
lines.append(" * hand-edit. Regenerate with:")
lines.append(" *   python3 software/soc/gen_npu_dma_workload.py > \\")
lines.append(" *                              software/soc/npu_dma_workload_data.h")
lines.append(f" * seed = {SEED} */")
lines.append("#ifndef NPU_DMA_WORKLOAD_DATA_H")
lines.append("#define NPU_DMA_WORKLOAD_DATA_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append(f"#define NPU_DMA_INPUT_DIM {INPUT_DIM}")
lines.append(f"#define NPU_DMA_OUT {OUT}")
lines.append("")
lines.append(f"static const int8_t npu_dma_activation[{INPUT_DIM}] = {{")
for i in range(0, INPUT_DIM, 16):
    lines.append("    " + ", ".join(str(x) for x in a[i:i+16]) + ",")
lines.append("};")
lines.append("")
lines.append(f"static const int8_t npu_dma_weights[NPU_DMA_OUT][{INPUT_DIM}] = {{")
for row in w:
    lines.append("    {")
    for i in range(0, INPUT_DIM, 16):
        lines.append("        " + ", ".join(str(x) for x in row[i:i+16]) + ",")
    lines.append("    },")
lines.append("};")
lines.append("")
lines.append("static const int32_t npu_dma_expected[NPU_DMA_OUT] = {")
lines.append("    " + ", ".join(str(x) for x in expected))
lines.append("};")
lines.append("")
lines.append("#endif /* NPU_DMA_WORKLOAD_DATA_H */")

print("\n".join(lines))
