// A slow, single-tap clock for a real ULX3S board test of CORE=ooo -
// nothing about this module is core-specific; it is generic "run the SoC
// slower than the board's own 25 MHz oscillator" infrastructure.
//
// ---- Why this exists ----
//
// docs/roadmap.md's "CORE=ooo has no Fmax" entry, Round 6: the
// combinational loop that made real synthesis fail outright is closed,
// but the real Fmax it uncovered underneath - 8.68 MHz - still fails the
// board's 25 MHz requirement by a wide margin. Flashing a design clocked
// faster than it can settle produces routine setup-time violations, not
// a working CPU. This PLL derives a clock the design's own measured
// timing can actually meet, so a real board test is possible before
// Round 7 - an RTL-level fix, the only kind still open now that Round
// 7's first idea (an SDC timing exception) checked out as not viable in
// nextpnr-ecp5 today - closes the real 25 MHz gap.
//
// ---- Why 5 MHz, and a real caveat about it ----
//
// A clean 1/5 division of the 25 MHz input (an exact integer ratio, the
// same reason fpga/video_pll.v's own header gives for choosing 125 MHz
// over the true 25.175 MHz DVI clock), and real margin - about 1.7x -
// below Round 6's own measured 8.68 MHz worst case, in case a fresh
// place-and-route at a different target lands somewhat worse than that
// figure did.
//
// `ecppll` printed a real warning generating this: "Output frequency
// 5MHz not in range (10MHz, 400MHz)" - worth stating plainly rather than
// hiding, since this project's own practice is to name what is uncertain
// rather than assume it away. The computed configuration itself is
// mechanically ordinary for the part - VCO 600 MHz sits comfortably
// inside the ECP5's normal EHXPLLL range, and CLKOP_DIV=120 is a valid
// divider value - so the warning reads as `ecppll`'s own generic "is
// this really what you meant" guardrail for its typical use cases
// (video/memory clocking, which rarely go this low), not a stated
// electrical limit. Not independently confirmed on real silicon by this
// change - that confirmation is exactly what flashing the resulting
// bitstream is for.
//
// ---- Where the parameters below came from ----
//
// Generated by the project's own toolchain, not hand-picked, the same
// discipline fpga/video_pll.v's own header already states:
//   ecppll -i 25 -n underclock_pll --clkin_name clk_25mhz \
//       --clkout0_name clk_soc --clkout0 5 -f fpga/underclock_pll.v
// (then hand-edited only to add this header and the simulation model
// below - `ecppll` emits the synthesis body verbatim otherwise).
//
// ---- Why no `locked` gating ----
//
// Matching this project's own already-established convention for its
// other two clock-primitive wrappers - fpga/video_pll.v and
// fpga/sdram_clk_out.v - neither of which gates anything on `locked`
// either (see fpga/video_out.v's own comment on the point). `locked` is
// still a real output here, in case a future board target needs it.
module underclock_pll (
    input  wire clk_25mhz,   // 25 MHz, 0 deg - the board's own oscillator
    output wire clk_soc,     // 5 MHz, 0 deg
    output wire locked
);
`ifdef SYNTHESIS
    (* FREQUENCY_PIN_CLKI="25" *)
    (* FREQUENCY_PIN_CLKOP="5" *)
    (* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *) (* MFG_ENABLE_FILTEROPAMP="1" *) (* MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA("DISABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(5),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(120),
        .CLKOP_CPHASE(60),
        .CLKOP_FPHASE(0),
        .FEEDBK_PATH("CLKOP"),
        .CLKFB_DIV(1)
    ) pll_i (
        .RST(1'b0),
        .STDBY(1'b0),
        .CLKI(clk_25mhz),
        .CLKOP(clk_soc),
        .CLKFB(clk_soc),
        .CLKINTFB(),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked)
    );
`else
    // Simulation. EHXPLLL has no behavioral model, and dividing a clock's
    // frequency needs new clock generation, not combinational logic -
    // but unlike fpga/video_pll.v (which derives both of its own taps
    // from one self-generated free-running reference, since neither
    // exists independently in a testbench), this module has exactly one
    // output, tapped straight off the real `clk_25mhz` input a testbench
    // already drives - so this simply divides that same signal directly.
    // Same comparator-based shape as fpga/video_pll.v's own identical
    // 5-cycle counter, not a toggle-per-N-cycles one: toggling `clk_soc`
    // only on `div_count`'s own wraparound doubles the period (two
    // toggles per output cycle), dividing by 10 instead of 5. Duty cycle
    // is not 50% (2 of 5 input cycles high) - matching
    // fpga/video_pll.v's own note that nothing downstream reads a
    // divided tap's duty cycle here either, only its edges, and the
    // edges land at the right rate.
    reg       clk_soc_r = 1'b0;
    reg [2:0] div_count = 3'd0;
    reg       locked_r  = 1'b0;

    always @(posedge clk_25mhz) begin
        div_count <= (div_count == 3'd4) ? 3'd0 : div_count + 3'd1;
        clk_soc_r <= (div_count < 3'd2);
    end

    // A real PLL takes real time to lock; a handful of input-clock cycles
    // is enough for anything in this project's simulation to see `locked`
    // rise rather than start high, without adding a multi-microsecond
    // wait no testbench actually needs - the same reasoning
    // fpga/video_pll.v's own identical block already gives.
    initial begin
        repeat (8) @(posedge clk_25mhz);
        locked_r = 1'b1;
    end

    assign clk_soc = clk_soc_r;
    assign locked  = locked_r;
`endif
endmodule
