// The video clock domain: a 5x-pixel-clock "bit clock" for the TMDS
// serializer, and the pixel clock itself, both from one PLL rather than two
// free-running ones.
//
// ---- Why one PLL with two taps, not clk_25mhz reused as the pixel clock ----
//
// A separate, free-running "clk_pixel" divided down from "clk_bit" in fabric
// (a plain counter) would work functionally, but ties the pixel clock's
// phase to wherever that counter happens to be after reset - arbitrary, and
// different on every power-up. `EHXPLLL` can emit both taps directly off the
// same VCO instead (`CLKOP`/`CLKOS` below), which gives a *fixed*, repeatable
// phase relationship between them - the property the TMDS serializer this
// eventually feeds needs to load a fresh 10-bit word at a known point in the
// bit clock's cycle, not one that drifts by reset.
//
// ---- Why 125 MHz and not the true 25.175 MHz DVI clock ----
//
// This SoC already runs its pixel clock at a plain 25 MHz rather than
// 25.175 MHz - `rtl/soc/video_timing.v`'s own header calls the 0.7%
// difference "deliberate and currently harmless" with no display attached.
// That choice pays off again here: 25 MHz x5 = 125 MHz is an exact integer
// ratio, so both `ecppll`'s search and the PLL's own divider land on it
// with no rounding - VCO 625 MHz, CLKOP (bit clock) = 625/5, CLKOS (pixel
// clock) = 625/25, both exact. The true 25.175 MHz clock would need a VCO
// frequency with no exact integer divisor for either tap.
//
// ---- Where the parameters below came from ----
//
// Generated by the project's own toolchain, not hand-picked:
//   ecppll -i 25 -n video_pll --clkin_name clk_25mhz \
//       --clkout0_name clk_bit --clkout0 125 \
//       --clkout1_name clk_pixel --clkout1 25 -f video_pll.v
// `ecppll`'s own output already documents this: "diamond 3.10 or higher is
// likely to abort" - a Lattice-toolchain compatibility note that does not
// apply here, since this project only ever builds with yosys/nextpnr-ecp5.
module video_pll (
    input  wire clk_25mhz,
    output wire clk_bit,      // 125 MHz - 5x clk_pixel, the serializer's SCLK
    output wire clk_pixel,    // 25 MHz - this SoC's existing pixel clock rate
    output wire locked
);
`ifdef SYNTHESIS
    (* FREQUENCY_PIN_CLKI="25" *)
    (* FREQUENCY_PIN_CLKOP="125" *)
    (* FREQUENCY_PIN_CLKOS="25" *)
    (* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *) (* MFG_ENABLE_FILTEROPAMP="1" *) (* MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA("DISABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(1),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(5),
        .CLKOP_CPHASE(2),
        .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"),
        .CLKOS_DIV(25),
        .CLKOS_CPHASE(2),
        .CLKOS_FPHASE(0),
        .FEEDBK_PATH("CLKOP"),
        .CLKFB_DIV(5)
    ) pll_i (
        .RST(1'b0),
        .STDBY(1'b0),
        .CLKI(clk_25mhz),
        .CLKOP(clk_bit),
        .CLKOS(clk_pixel),
        .CLKFB(clk_bit),
        .CLKINTFB(),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked)
    );
`else
    // Simulation. EHXPLLL has no behavioral model, and multiplying a clock's
    // frequency needs new clock generation, not combinational logic - so
    // this free-runs its own 125 MHz and divides it down for the 25 MHz tap,
    // the same shared-source relationship the real PLL gives (both taps
    // moving together, never drifting apart), rather than two independent
    // clocks that happen to start at the right ratio. Duty cycle on the
    // divided tap is not 50% (2 of 5 bit-clock cycles high) - real EHXPLLL
    // hardware handles the division properly; nothing downstream reads
    // `clk_pixel`'s duty cycle, only its edges, and the edges land at the
    // right rate.
    reg        clk_bit_r   = 1'b0;
    reg        clk_pixel_r = 1'b0;
    reg [2:0]  div_count   = 3'd0;
    reg        locked_r    = 1'b0;

    always #4 clk_bit_r = ~clk_bit_r;   // 125 MHz: 8 ns period, #4 half-period

    always @(posedge clk_bit_r) begin
        div_count   <= (div_count == 3'd4) ? 3'd0 : div_count + 3'd1;
        clk_pixel_r <= (div_count < 3'd2);
    end

    // A real PLL takes real time to lock; a handful of bit-clock cycles is
    // enough for anything in this project's simulation to see `locked` rise
    // rather than start high, without adding a multi-microsecond wait no
    // testbench actually needs.
    initial begin
        repeat (8) @(posedge clk_bit_r);
        locked_r = 1'b1;
    end

    assign clk_bit   = clk_bit_r;
    assign clk_pixel = clk_pixel_r;
    assign locked    = locked_r;
`endif
endmodule
