#!/usr/bin/env python3
"""Derive pairing.S's expected accumulator, and emit it as a header.

Generated rather than pasted, on purpose. The value this test compares
against has to come from the *definition* of the arithmetic, never from what
a core printed - a constant captured off a run turns a self-checking test
into a change detector that certifies whatever the hardware did the first
time. Keeping it in a script means the derivation is the artifact and the
number is a build product.

Usage: expected.py > expected.h
"""
import sys

ITERS = 2048
KDIV = 1000003
MASK = 0xFFFFFFFF


def accumulator():
    acc = 0
    for i in range(ITERS):
        acc += (i + 0x111) & MASK          # addi
        acc += i ^ 0x222                   # xori
        acc += i | 0x333                   # ori
        acc += i & 0x444                   # andi
        acc += (i + KDIV) // KDIV          # divu; 1 for every i < KDIV
        acc &= MASK
    return acc


def main():
    if ITERS > KDIV:
        sys.exit("expected.py: the quotient is only 1 while ITERS <= KDIV")
    out = sys.stdout
    out.write("/* Generated by tests/vernier/expected.py - do not edit. */\n")
    out.write(f"#define ITERS         {ITERS}\n")
    out.write(f"#define KDIV          {KDIV}\n")
    out.write(f"#define EXPECTED_ACC  0x{accumulator():08x}\n")


if __name__ == "__main__":
    main()
